name: skidder-openvpn # you probably want to 'snapcraft register <name>'
version: '2.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: OpenVPN is an open source VPN daemon http://openvpn.net # 79 char long summary
description: |
  OpenVPN -- A Secure tunneling daemon

  Copyright (C) 2002-2010 OpenVPN Technologies, Inc. This program is free software;
  you can redistribute it and/or modify
  it under the terms of the GNU General Public License version 2
  as published by the Free Software Foundation

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  openvpn:
    command: bin/openvpn

parts:
  openvpn:
    # Clone and build
    plugin: autotools
    source: https://github.com/OpenVPN/openvpn.git
    source-branch: release/2.4
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libssl-dev
      - liblzo2-dev
      - libpam0g-dev
    organize:
      sbin/openvpn: bin/openvpn
